# Generated by Django 5.2.16 on 2026-10-07 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_restore_tz_shifted_media_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGDBGameMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='igdb_game_metadata', to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='IGDBGameTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('genre', 'Genre'), ('theme', 'Theme'), ('keyword', 'Keyword')], max_length=12)),
                ('provider_id', models.PositiveBigIntegerField()),
                ('name', models.TextField()),
                ('slug', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'provider_id'), name='unique_igdb_taxonomy_kind_id')],
            },
        ),
        migrations.CreateModel(
            name='IGDBGameTaxonomyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_assignments', to='app.igdbgamemetadata')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_assignments', to='app.igdbgametaxonomy')),
            ],
        ),
        migrations.AddField(
            model_name='igdbgamemetadata',
            name='taxonomies',
            field=models.ManyToManyField(related_name='game_metadata', through='app.IGDBGameTaxonomyAssignment', to='app.igdbgametaxonomy'),
        ),
        migrations.AddConstraint(
            model_name='igdbgametaxonomyassignment',
            constraint=models.UniqueConstraint(fields=('metadata', 'taxonomy'), name='unique_igdb_game_taxonomy_assignment'),
        ),
    ]
