# Generated by Django 5.2.16 on 2026-10-07 22:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_igdbgamemetadata_igdbgametaxonomy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDBMovieMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tmdb_movie_metadata', to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='TMDBMovieTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('genre', 'Genre'), ('keyword', 'Keyword')], max_length=12)),
                ('provider_id', models.PositiveBigIntegerField()),
                ('name', models.TextField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'provider_id'), name='unique_tmdb_movie_taxonomy_kind_id')],
            },
        ),
        migrations.CreateModel(
            name='TMDBMovieTaxonomyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_assignments', to='app.tmdbmoviemetadata')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_assignments', to='app.tmdbmovietaxonomy')),
            ],
        ),
        migrations.AddField(
            model_name='tmdbmoviemetadata',
            name='taxonomies',
            field=models.ManyToManyField(related_name='movie_metadata', through='app.TMDBMovieTaxonomyAssignment', to='app.tmdbmovietaxonomy'),
        ),
        migrations.AddConstraint(
            model_name='tmdbmovietaxonomyassignment',
            constraint=models.UniqueConstraint(fields=('metadata', 'taxonomy'), name='unique_tmdb_movie_taxonomy_assignment'),
        ),
    ]
