# Generated by Django 5.2.16 on 2026-10-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_tmdbmoviemetadata_tmdbmovietaxonomy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbmoviemetadata',
            name='last_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmdbmoviemetadata',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
