# Generated by Django 5.2.16 on 2026-10-08 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_tmdbmoviemetadata_last_attempted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDBMovieCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.PositiveBigIntegerField(unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TMDBMovieCreditAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(choices=[('cast', 'Cast'), ('crew', 'Crew')], max_length=8)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('character', models.CharField(blank=True, default='', max_length=255)),
                ('cast_order', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_assignments', to='app.tmdbmoviemetadata')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_assignments', to='app.tmdbmoviecredit')),
            ],
        ),
        migrations.AddField(
            model_name='tmdbmoviemetadata',
            name='credits',
            field=models.ManyToManyField(related_name='movie_metadata', through='app.TMDBMovieCreditAssignment', to='app.tmdbmoviecredit'),
        ),
        migrations.AddIndex(
            model_name='tmdbmoviecreditassignment',
            index=models.Index(fields=['credit_type', 'job', 'person'], name='tmdb_credit_role_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='tmdbmoviecreditassignment',
            constraint=models.UniqueConstraint(fields=('metadata', 'person', 'credit_type', 'job', 'character'), name='unique_tmdb_movie_credit_assignment'),
        ),
    ]
