# Generated by Django 5.2.16 on 2026-10-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_tmdbmoviecredit_tmdbmoviecreditassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbmoviemetadata',
            name='credits_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
