# Generated by Django 5.2.16 on 2026-10-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_user_default_edit_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='include_unknown_taxonomy',
            field=models.BooleanField(default=False, help_text='Allow taxonomy exclusions to include items with unknown taxonomy'),
        ),
    ]
